In [2]:
from pyrotoolbox import parse

In [4]:
ls 'testdata/fireplate_workbench_V1.5.7.2519'

'_FirePlate-O2_( Gr.1)_OpticalTemp.txt'*
'_FirePlate-O2_( Gr.2)_Oxygen.txt'*
'_FirePlate-O2_( P1)_InternalPressure.txt'*

In [11]:
df, m = parse("testdata/fireplate_workbench_V1.5.7.2519/_FirePlate-O2_( Gr.1)_OpticalTemp.txt")

ValueError: Settings and Calibration section not found in logfile

In [13]:
df.iloc[1].to_dict()

{'time_s': 30.319,
 'A01_pH': 6.208,
 'A01_dphi': 23.744,
 'A01_signal_intensity': 248.0,
 'A01_ambient_light': 19.0,
 'A01_R': 1.3704,
 'A01_status': 0.0,
 'A02_pH': 6.2,
 'A02_dphi': 23.706,
 'A02_signal_intensity': 255.0,
 'A02_ambient_light': 19.0,
 'A02_R': 1.3738,
 'A02_status': 0.0,
 'A03_pH': 6.134,
 'A03_dphi': 23.399,
 'A03_signal_intensity': 253.0,
 'A03_ambient_light': 19.0,
 'A03_R': 1.4018,
 'A03_status': 0.0,
 'A04_pH': 6.209,
 'A04_dphi': 23.748,
 'A04_signal_intensity': 247.0,
 'A04_ambient_light': 18.0,
 'A04_R': 1.37,
 'A04_status': 0.0,
 'A05_pH': 6.157,
 'A05_dphi': 23.5,
 'A05_signal_intensity': 274.0,
 'A05_ambient_light': 19.0,
 'A05_R': 1.3925,
 'A05_status': 0.0,
 'A06_pH': 6.206,
 'A06_dphi': 23.734,
 'A06_signal_intensity': 232.0,
 'A06_ambient_light': 19.0,
 'A06_R': 1.3713,
 'A06_status': 0.0,
 'A07_pH': 6.248,
 'A07_dphi': 23.949,
 'A07_signal_intensity': 225.0,
 'A07_ambient_light': 19.0,
 'A07_R': 1.3521,
 'A07_status': 0.0,
 'A08_pH': 6.022,
 'A08_dphi': 22.965,
 'A08_signal_intensity': 234.0,
 'A08_ambient_light': 18.0,
 'A08_R': 1.4425,
 'A08_status': 0.0,
 'A09_pH': 6.084,
 'A09_dphi': 23.193,
 'A09_signal_intensity': 225.0,
 'A09_ambient_light': 18.0,
 'A09_R': 1.4209,
 'A09_status': 0.0,
 'A10_pH': 6.146,
 'A10_dphi': 23.451,
 'A10_signal_intensity': 240.0,
 'A10_ambient_light': 19.0,
 'A10_R': 1.397,
 'A10_status': 0.0,
 'A11_pH': 6.224,
 'A11_dphi': 23.824,
 'A11_signal_intensity': 202.0,
 'A11_ambient_light': 18.0,
 'A11_R': 1.3632,
 'A11_status': 0.0,
 'A12_pH': 6.16,
 'A12_dphi': 23.516,
 'A12_signal_intensity': 220.0,
 'A12_ambient_light': 18.0,
 'A12_R': 1.391,
 'A12_status': 0.0,
 'B01_pH': 6.17,
 'B01_dphi': 23.562,
 'B01_signal_intensity': 232.0,
 'B01_ambient_light': 19.0,
 'B01_R': 1.3868,
 'B01_status': 0.0,
 'B02_pH': 6.139,
 'B02_dphi': 23.422,
 'B02_signal_intensity': 213.0,
 'B02_ambient_light': 18.0,
 'B02_R': 1.3997,
 'B02_status': 0.0,
 'B03_pH': 6.11,
 'B03_dphi': 23.299,
 'B03_signal_intensity': 249.0,
 'B03_ambient_light': 17.0,
 'B03_R': 1.411,
 'B03_status': 0.0,
 'B04_pH': 6.106,
 'B04_dphi': 23.281,
 'B04_signal_intensity': 225.0,
 'B04_ambient_light': 18.0,
 'B04_R': 1.4127,
 'B04_status': 0.0,
 'B05_pH': 6.174,
 'B05_dphi': 23.578,
 'B05_signal_intensity': 243.0,
 'B05_ambient_light': 18.0,
 'B05_R': 1.3854,
 'B05_status': 0.0,
 'B06_pH': 6.059,
 'B06_dphi': 23.098,
 'B06_signal_intensity': 218.0,
 'B06_ambient_light': 18.0,
 'B06_R': 1.4299,
 'B06_status': 0.0,
 'B07_pH': 6.065,
 'B07_dphi': 23.12,
 'B07_signal_intensity': 217.0,
 'B07_ambient_light': 17.0,
 'B07_R': 1.4278,
 'B07_status': 0.0,
 'B08_pH': 6.013,
 'B08_dphi': 22.933,
 'B08_signal_intensity': 216.0,
 'B08_ambient_light': 17.0,
 'B08_R': 1.4456,
 'B08_status': 0.0,
 'B09_pH': 6.099,
 'B09_dphi': 23.252,
 'B09_signal_intensity': 218.0,
 'B09_ambient_light': 18.0,
 'B09_R': 1.4154,
 'B09_status': 0.0,
 'B10_pH': 6.095,
 'B10_dphi': 23.238,
 'B10_signal_intensity': 214.0,
 'B10_ambient_light': 17.0,
 'B10_R': 1.4167,
 'B10_status': 0.0,
 'B11_pH': 6.078,
 'B11_dphi': 23.172,
 'B11_signal_intensity': 214.0,
 'B11_ambient_light': 17.0,
 'B11_R': 1.4229,
 'B11_status': 0.0,
 'B12_pH': 6.147,
 'B12_dphi': 23.457,
 'B12_signal_intensity': 222.0,
 'B12_ambient_light': 18.0,
 'B12_R': 1.3964,
 'B12_status': 0.0,
 'C01_pH': 6.199,
 'C01_dphi': 23.701,
 'C01_signal_intensity': 249.0,
 'C01_ambient_light': 18.0,
 'C01_R': 1.3742,
 'C01_status': 0.0,
 'C02_pH': 6.032,
 'C02_dphi': 22.999,
 'C02_signal_intensity': 240.0,
 'C02_ambient_light': 18.0,
 'C02_R': 1.4393,
 'C02_status': 0.0,
 'C03_pH': 6.1,
 'C03_dphi': 23.257,
 'C03_signal_intensity': 256.0,
 'C03_ambient_light': 17.0,
 'C03_R': 1.415,
 'C03_status': 0.0,
 'C04_pH': 6.052,
 'C04_dphi': 23.071,
 'C04_signal_intensity': 248.0,
 'C04_ambient_light': 18.0,
 'C04_R': 1.4324,
 'C04_status': 0.0,
 'C05_pH': 6.04,
 'C05_dphi': 23.03,
 'C05_signal_intensity': 218.0,
 'C05_ambient_light': 18.0,
 'C05_R': 1.4363,
 'C05_status': 0.0,
 'C06_pH': 6.031,
 'C06_dphi': 22.996,
 'C06_signal_intensity': 240.0,
 'C06_ambient_light': 17.0,
 'C06_R': 1.4396,
 'C06_status': 0.0,
 'C07_pH': 6.125,
 'C07_dphi': 23.362,
 'C07_signal_intensity': 230.0,
 'C07_ambient_light': 17.0,
 'C07_R': 1.4052,
 'C07_status': 0.0,
 'C08_pH': 6.083,
 'C08_dphi': 23.189,
 'C08_signal_intensity': 217.0,
 'C08_ambient_light': 18.0,
 'C08_R': 1.4213,
 'C08_status': 0.0,
 'C09_pH': 6.136,
 'C09_dphi': 23.407,
 'C09_signal_intensity': 209.0,
 'C09_ambient_light': 17.0,
 'C09_R': 1.401,
 'C09_status': 0.0,
 'C10_pH': 6.227,
 'C10_dphi': 23.839,
 'C10_signal_intensity': 230.0,
 'C10_ambient_light': 18.0,
 'C10_R': 1.3619,
 'C10_status': 0.0,
 'C11_pH': 6.034,
 'C11_dphi': 23.009,
 'C11_signal_intensity': 219.0,
 'C11_ambient_light': 18.0,
 'C11_R': 1.4383,
 'C11_status': 0.0,
 'C12_pH': 6.194,
 'C12_dphi': 23.674,
 'C12_signal_intensity': 217.0,
 'C12_ambient_light': 17.0,
 'C12_R': 1.3767,
 'C12_status': 0.0,
 'D01_pH': 6.158,
 'D01_dphi': 23.508,
 'D01_signal_intensity': 265.0,
 'D01_ambient_light': 18.0,
 'D01_R': 1.3918,
 'D01_status': 0.0,
 'D02_pH': 6.126,
 'D02_dphi': 23.364,
 'D02_signal_intensity': 241.0,
 'D02_ambient_light': 17.0,
 'D02_R': 1.405,
 'D02_status': 0.0,
 'D03_pH': 6.212,
 'D03_dphi': 23.766,
 'D03_signal_intensity': 253.0,
 'D03_ambient_light': 17.0,
 'D03_R': 1.3684,
 'D03_status': 0.0,
 'D04_pH': 6.114,
 'D04_dphi': 23.316,
 'D04_signal_intensity': 237.0,
 'D04_ambient_light': 17.0,
 'D04_R': 1.4095,
 'D04_status': 0.0,
 'D05_pH': 6.146,
 'D05_dphi': 23.452,
 'D05_signal_intensity': 242.0,
 'D05_ambient_light': 18.0,
 'D05_R': 1.3969,
 'D05_status': 0.0,
 'D06_pH': 6.191,
 'D06_dphi': 23.661,
 'D06_signal_intensity': 265.0,
 'D06_ambient_light': 18.0,
 'D06_R': 1.3779,
 'D06_status': 0.0,
 'D07_pH': 6.206,
 'D07_dphi': 23.735,
 'D07_signal_intensity': 272.0,
 'D07_ambient_light': 17.0,
 'D07_R': 1.3712,
 'D07_status': 0.0,
 'D08_pH': 6.09,
 'D08_dphi': 23.219,
 'D08_signal_intensity': 244.0,
 'D08_ambient_light': 17.0,
 'D08_R': 1.4185,
 'D08_status': 0.0,
 'D09_pH': 6.045,
 'D09_dphi': 23.048,
 'D09_signal_intensity': 249.0,
 'D09_ambient_light': 17.0,
 'D09_R': 1.4346,
 'D09_status': 0.0,
 'D10_pH': 6.19,
 'D10_dphi': 23.656,
 'D10_signal_intensity': 277.0,
 'D10_ambient_light': 18.0,
 'D10_R': 1.3783,
 'D10_status': 0.0,
 'D11_pH': 6.042,
 'D11_dphi': 23.035,
 'D11_signal_intensity': 221.0,
 'D11_ambient_light': 18.0,
 'D11_R': 1.4359,
 'D11_status': 0.0,
 'D12_pH': 6.031,
 'D12_dphi': 22.998,
 'D12_signal_intensity': 244.0,
 'D12_ambient_light': 17.0,
 'D12_R': 1.4394,
 'D12_status': 0.0,
 'E01_pH': 6.139,
 'E01_dphi': 23.42,
 'E01_signal_intensity': 248.0,
 'E01_ambient_light': 18.0,
 'E01_R': 1.3998,
 'E01_status': 0.0,
 'E02_pH': 6.166,
 'E02_dphi': 23.543,
 'E02_signal_intensity': 269.0,
 'E02_ambient_light': 17.0,
 'E02_R': 1.3886,
 'E02_status': 0.0,
 'E03_pH': 6.203,
 'E03_dphi': 23.721,
 'E03_signal_intensity': 256.0,
 'E03_ambient_light': 17.0,
 'E03_R': 1.3724,
 'E03_status': 0.0,
 'E04_pH': 6.102,
 'E04_dphi': 23.268,
 'E04_signal_intensity': 276.0,
 'E04_ambient_light': 17.0,
 'E04_R': 1.4139,
 'E04_status': 0.0,
 'E05_pH': 6.134,
 'E05_dphi': 23.399,
 'E05_signal_intensity': 250.0,
 'E05_ambient_light': 17.0,
 'E05_R': 1.4018,
 'E05_status': 0.0,
 'E06_pH': 6.079,
 'E06_dphi': 23.174,
 'E06_signal_intensity': 270.0,
 'E06_ambient_light': 17.0,
 'E06_R': 1.4227,
 'E06_status': 0.0,
 'E07_pH': 6.19,
 'E07_dphi': 23.655,
 'E07_signal_intensity': 264.0,
 'E07_ambient_light': 17.0,
 'E07_R': 1.3784,
 'E07_status': 0.0,
 'E08_pH': 6.146,
 'E08_dphi': 23.453,
 'E08_signal_intensity': 260.0,
 'E08_ambient_light': 17.0,
 'E08_R': 1.3968,
 'E08_status': 0.0,
 'E09_pH': 6.077,
 'E09_dphi': 23.167,
 'E09_signal_intensity': 248.0,
 'E09_ambient_light': 17.0,
 'E09_R': 1.4234,
 'E09_status': 0.0,
 'E10_pH': 6.143,
 'E10_dphi': 23.441,
 'E10_signal_intensity': 270.0,
 'E10_ambient_light': 17.0,
 'E10_R': 1.3979,
 'E10_status': 0.0,
 'E11_pH': 6.098,
 'E11_dphi': 23.248,
 'E11_signal_intensity': 248.0,
 'E11_ambient_light': 17.0,
 'E11_R': 1.4158,
 'E11_status': 0.0,
 'E12_pH': 6.148,
 'E12_dphi': 23.46,
 'E12_signal_intensity': 238.0,
 'E12_ambient_light': 18.0,
 'E12_R': 1.3962,
 'E12_status': 0.0,
 'F01_pH': 6.155,
 'F01_dphi': 23.494,
 'F01_signal_intensity': 263.0,
 'F01_ambient_light': 18.0,
 'F01_R': 1.393,
 'F01_status': 0.0,
 'F02_pH': 6.245,
 'F02_dphi': 23.934,
 'F02_signal_intensity': 269.0,
 'F02_ambient_light': 18.0,
 'F02_R': 1.3535,
 'F02_status': 0.0,
 'F03_pH': 6.266,
 'F03_dphi': 24.048,
 'F03_signal_intensity': 260.0,
 'F03_ambient_light': 18.0,
 'F03_R': 1.3434,
 'F03_status': 0.0,
 'F04_pH': 6.268,
 'F04_dphi': 24.061,
 'F04_signal_intensity': 231.0,
 'F04_ambient_light': 18.0,
 'F04_R': 1.3423,
 'F04_status': 0.0,
 'F05_pH': 6.231,
 'F05_dphi': 23.862,
 'F05_signal_intensity': 272.0,
 'F05_ambient_light': 17.0,
 'F05_R': 1.3598,
 'F05_status': 0.0,
 'F06_pH': 6.184,
 'F06_dphi': 23.627,
 'F06_signal_intensity': 260.0,
 'F06_ambient_light': 18.0,
 'F06_R': 1.3809,
 'F06_status': 0.0,
 'F07_pH': 6.113,
 'F07_dphi': 23.312,
 'F07_signal_intensity': 259.0,
 'F07_ambient_light': 17.0,
 'F07_R': 1.4098,
 'F07_status': 0.0,
 'F08_pH': 6.16,
 'F08_dphi': 23.515,
 'F08_signal_intensity': 286.0,
 'F08_ambient_light': 17.0,
 'F08_R': 1.3911,
 'F08_status': 0.0,
 'F09_pH': 6.11,
 'F09_dphi': 23.297,
 'F09_signal_intensity': 276.0,
 'F09_ambient_light': 17.0,
 'F09_R': 1.4112,
 'F09_status': 0.0,
 'F10_pH': 6.241,
 'F10_dphi': 23.913,
 'F10_signal_intensity': 262.0,
 'F10_ambient_light': 17.0,
 'F10_R': 1.3553,
 'F10_status': 0.0,
 'F11_pH': 6.141,
 'F11_dphi': 23.432,
 'F11_signal_intensity': 267.0,
 'F11_ambient_light': 17.0,
 'F11_R': 1.3987,
 'F11_status': 0.0,
 'F12_pH': 6.208,
 'F12_dphi': 23.743,
 'F12_signal_intensity': 273.0,
 'F12_ambient_light': 18.0,
 'F12_R': 1.3705,
 'F12_status': 0.0,
 'G01_pH': 6.051,
 'G01_dphi': 23.069,
 'G01_signal_intensity': 308.0,
 'G01_ambient_light': 18.0,
 'G01_R': 1.4326,
 'G01_status': 0.0,
 'G02_pH': 6.186,
 'G02_dphi': 23.638,
 'G02_signal_intensity': 277.0,
 'G02_ambient_light': 18.0,
 'G02_R': 1.3799,
 'G02_status': 0.0,
 'G03_pH': 6.199,
 'G03_dphi': 23.699,
 'G03_signal_intensity': 245.0,
 'G03_ambient_light': 18.0,
 'G03_R': 1.3744,
 'G03_status': 0.0,
 'G04_pH': 6.19,
 'G04_dphi': 23.654,
 'G04_signal_intensity': 250.0,
 'G04_ambient_light': 17.0,
 'G04_R': 1.3785,
 'G04_status': 0.0,
 'G05_pH': 6.219,
 'G05_dphi': 23.801,
 'G05_signal_intensity': 247.0,
 'G05_ambient_light': 17.0,
 'G05_R': 1.3653,
 'G05_status': 0.0,
 'G06_pH': 6.195,
 'G06_dphi': 23.681,
 'G06_signal_intensity': 241.0,
 'G06_ambient_light': 17.0,
 'G06_R': 1.376,
 'G06_status': 0.0,
 'G07_pH': 6.235,
 'G07_dphi': 23.885,
 'G07_signal_intensity': 248.0,
 'G07_ambient_light': 17.0,
 'G07_R': 1.3578,
 'G07_status': 0.0,
 'G08_pH': 6.126,
 'G08_dphi': 23.365,
 'G08_signal_intensity': 282.0,
 'G08_ambient_light': 18.0,
 'G08_R': 1.4049,
 'G08_status': 0.0,
 'G09_pH': 6.21,
 'G09_dphi': 23.752,
 'G09_signal_intensity': 230.0,
 'G09_ambient_light': 18.0,
 'G09_R': 1.3697,
 'G09_status': 0.0,
 'G10_pH': 6.235,
 'G10_dphi': 23.884,
 'G10_signal_intensity': 209.0,
 'G10_ambient_light': 17.0,
 'G10_R': 1.3579,
 'G10_status': 0.0,
 'G11_pH': 6.092,
 'G11_dphi': 23.226,
 'G11_signal_intensity': 222.0,
 'G11_ambient_light': 17.0,
 'G11_R': 1.4178,
 'G11_status': 0.0,
 'G12_pH': 6.22,
 'G12_dphi': 23.807,
 'G12_signal_intensity': 215.0,
 'G12_ambient_light': 17.0,
 'G12_R': 1.3647,
 'G12_status': 0.0,
 'H01_pH': 6.05,
 'H01_dphi': 23.067,
 'H01_signal_intensity': 270.0,
 'H01_ambient_light': 18.0,
 'H01_R': 1.4328,
 'H01_status': 0.0,
 'H02_pH': 6.174,
 'H02_dphi': 23.581,
 'H02_signal_intensity': 262.0,
 'H02_ambient_light': 18.0,
 'H02_R': 1.3851,
 'H02_status': 0.0,
 'H03_pH': 6.175,
 'H03_dphi': 23.585,
 'H03_signal_intensity': 252.0,
 'H03_ambient_light': 17.0,
 'H03_R': 1.3847,
 'H03_status': 0.0,
 'H04_pH': 6.216,
 'H04_dphi': 23.786,
 'H04_signal_intensity': 275.0,
 'H04_ambient_light': 18.0,
 'H04_R': 1.3666,
 'H04_status': 0.0,
 'H05_pH': 6.186,
 'H05_dphi': 23.638,
 'H05_signal_intensity': 240.0,
 'H05_ambient_light': 17.0,
 'H05_R': 1.3799,
 'H05_status': 0.0,
 'H06_pH': 6.125,
 'H06_dphi': 23.361,
 'H06_signal_intensity': 238.0,
 'H06_ambient_light': 18.0,
 'H06_R': 1.4053,
 'H06_status': 0.0,
 'H07_pH': 6.285,
 'H07_dphi': 24.157,
 'H07_signal_intensity': 254.0,
 'H07_ambient_light': 17.0,
 'H07_R': 1.3339,
 'H07_status': 0.0,
 'H08_pH': 6.242,
 'H08_dphi': 23.92,
 'H08_signal_intensity': 247.0,
 'H08_ambient_light': 17.0,
 'H08_R': 1.3547,
 'H08_status': 0.0,
 'H09_pH': 6.086,
 'H09_dphi': 23.203,
 'H09_signal_intensity': 246.0,
 'H09_ambient_light': 17.0,
 'H09_R': 1.42,
 'H09_status': 0.0,
 'H10_pH': 6.235,
 'H10_dphi': 23.884,
 'H10_signal_intensity': 243.0,
 'H10_ambient_light': 18.0,
 'H10_R': 1.3579,
 'H10_status': 0.0,
 'H11_pH': 6.237,
 'H11_dphi': 23.893,
 'H11_signal_intensity': 257.0,
 'H11_ambient_light': 17.0,
 'H11_R': 1.3571,
 'H11_status': 0.0,
 'H12_pH': 6.148,
 'H12_dphi': 23.461,
 'H12_signal_intensity': 262.0,
 'H12_ambient_light': 18.0,
 'H12_R': 1.3961,
 'H12_status': 0.0,
 'case_temperature': 27.322}

In [18]:
df['Comment'].dropna()

Series([], Name: Comment, dtype: float64)

In [25]:
import pandas as pd
pd.read_csv("testdata/FDO2_Logger_145/FDO2 2025-07-01 12'39'09 ID2479F6055E9BDBD4.txt", skiprows=12, encoding='latin1', 
            sep='\t', decimal=',', index_col=False)

,2025-07-01 12:39:34,"0,3","171,014000","30,000000",0,"22,791000","408,450000","31,326000","977,522000","38,887000",Unnamed: 10,Unnamed: 11
0,2025-07-01 12:39:35,1.3,171.441,30.000,0,22.762,408.314,31.244,977.579,38.899,NaN,NaN
1,2025-07-01 12:39:36,2.4,171.470,30.000,0,22.760,408.022,31.186,977.594,38.900,NaN,NaN
2,2025-07-01 12:39:37,3.4,171.766,30.000,0,22.740,407.754,31.076,977.553,38.889,NaN,NaN
3,2025-07-01 12:39:38,4.4,172.002,30.000,0,22.724,407.342,32.345,977.594,38.875,NaN,NaN
4,2025-07-01 12:39:39,5.4,172.195,30.000,0,22.711,406.930,32.488,977.579,38.875,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
476,2025-07-01 12:47:42,488.2,178.444,39.875,0,21.299,358.960,1324.276,977.415,35.830,NaN,NaN
477,2025-07-01 12:47:43,489.3,178.144,39.843,0,21.321,358.968,1332.531,977.304,35.864,NaN,NaN
478,2025-07-01 12:47:44,490.3,178.365,39.781,0,21.313,359.140,1335.650,977.381,35.885,NaN,NaN
479,2025-07-01 12:47:45,491.3,177.969,39.750,0,21.341,359.096,1328.308,977.422,35.908,NaN,NaN
480,2025-07-01 12:47:46,492.3,178.557,39.718,0,21.307,359.296,1321.180,977.390,35.917,NaN,NaN

In [20]:
df.iloc[10].to_dict()

{'time_s': 10.5,
 'oxygen_hPa': 172.804,
 'sample_temperature': 30.0,
 'status': 0.0,
 'dphi': 22.67,
 'signal_intensity': 405.922,
 'ambient_light': 32.218,
 'pressure': 977.568,
 'humidity': 38.853,
 'Comment': nan}

In [6]:
import numpy as np
{k: np.nan if np.isnan(v) else v for k, v in df.iloc[1].to_dict().items()}

{'time_s': 1.3,
 'oxygen_hPa': 171.441,
 'sample_temperature': 30.0,
 'status': 0.0,
 'dphi': 22.762,
 'signal_intensity': 408.314,
 'ambient_light': 31.244,
 'pressure': 977.579,
 'humidity': 38.899,
 'Comment': nan}

In [7]:
ls 'testdata/workbench_V1.5.4.2482/2025-03-24_154458_Test_WB1452482/MeasurementData/'

'A_Firesting Pro (4 Channels)_(A Ch.1)_Oxygen.txt'*
'A_Firesting Pro (4 Channels)_(A Ch.2)_OpticalTemp.txt'*
'A_Firesting Pro (4 Channels)_(A Ch.3)_pH.txt'*
'A_Firesting Pro (4 Channels)_(A Ch.4)_Oxygen.txt'*
'A_Firesting Pro (4 Channels)_(A T1)_TempPT100Port.txt'*
'B_APHOX-LX_(B Ch.1)_pH.txt'*
'B_APHOX-LX_(B T1)_TempPT100Port.txt'*
'C_APHOX-TX_(C Ch.1)_Oxygen.txt'*
'C_APHOX-TX_(C T1)_TempPT100Port.txt'*
 Comments/
'D_PICO-O2_(D Ch.1)_Oxygen.txt'*
 StatusLegend.txt*

In [8]:
df, m = parse('testdata/workbench_V1.5.4.2482/2025-03-24_154458_Test_WB1452482/MeasurementData/A_Firesting Pro (4 Channels)_(A Ch.1)_Oxygen.txt')

In [9]:
file = '2025-03-24_154458_Test_WB1452482/MeasurementData/A_Firesting Pro (4 Channels)_(A Ch.4)_Oxygen.txt'
df, m = parse('testdata/workbench_V1.5.4.2482/' + file)
print(f"""        file1 = '{file}'
        df, m = read_workbench(self.directory + file1)
        self.assertEqual({m},
                         m)
        self.assertEqual({list(df.columns)}, list(df.columns))
        self.assertEqual({len(df)}, len(df))
        self.assertDictEqual(
            {df.iloc[1].to_dict()},
            {{k: np.nan if np.isnan(v) else v for k, v in df.iloc[1].to_dict().items()}})
""")

        file1 = '2025-03-24_154458_Test_WB1452482/MeasurementData/A_Firesting Pro (4 Channels)_(A Ch.4)_Oxygen.txt'
        df, m = read_workbench(self.directory + file1)
        self.assertEqual({'experiment_name': 'Test_WB1452482', 'experiment_description': '\n', 'software_version': 'Workbench V1.5.4.2482', 'device': 'FireSting-PRO [A] FSPRO-4', 'device_serial': '23390005', 'uid': '241642085AC9AE27', 'firmware': '4.11:001', 'channel': 4, 'sensor_code': 'SC7-530-209', 'settings': {'duration': '16 ms', 'intensity': '20%', 'amp': '400x', 'frequency': 4000, 'crc_enable': False, 'write_lock': False, 'auto_flash_duration': True, 'auto_amp': True, 'analyte': 'oxygen', 'fiber_type': '1 mm', 'temperature': 'external sensor', 'pressure': 'internal sensor', 'salinity': 7.5, 'fiber_length_mm': 1000}, 'calibration': {'date_calibration_high': datetime.datetime(2025, 3, 24, 0, 0), 'date_calibration_zero': None, 'dphi100': 21.776, 'dphi0': 53.0, 'f': 0.804, 'm': 0.09568, 'freq': 4000.0, 'tt': -0.000817, 'kt': 0.00969, 'bkgdAmpl': 0.584349, 'bkgdDphi': 0.0, 'mt': -6e-06, 'pressure': 993.907, 'temp100': 22.0, 'humidity': 100.0, 'temp0': 20.0, 'percentO2': 20.95}},
                         m)
        self.assertEqual(['time_s', 'oxygen_%airsat', 'dphi', 'signal_intensity', 'ambient_light', 'status', 'sample_temperature', 'pressure'], list(df.columns))
        self.assertEqual(213, len(df))
        self.assertDictEqual(
            {'time_s': 1.373, 'oxygen_%airsat': 97.897, 'dphi': 21.781, 'signal_intensity': 245.0, 'ambient_light': 1.0, 'status': 0.0, 'sample_temperature': 24.278, 'pressure': 994.0},
            {k: np.nan if np.isnan(v) else v for k, v in df.iloc[1].to_dict().items()})

In [19]:
df, m = parse('testdata/workbench_V1.5.4.2482/2025-03-24_154458_Test_WB1452482/MeasurementData/A_Firesting Pro (4 Channels)_(A Ch.2)_OpticalTemp.txt')

Warning! Unknown Workbench version! Please update pyrotoolbox.

In [22]:
df, m = parse('testdata/workbench_V1.5.4.2482/2025-03-24_154458_Test_WB1452482/MeasurementData/A_Firesting Pro (4 Channels)_(A Ch.3)_pH.txt')

Warning! Unknown Workbench version! Please update pyrotoolbox.

In [25]:
df, m = parse('testdata/workbench_V1.5.4.2482/2025-03-24_154458_Test_WB1452482/MeasurementData/A_Firesting Pro (4 Channels)_(A Ch.4)_Oxygen.txt')

Warning! Unknown Workbench version! Please update pyrotoolbox.

In [8]:
m

{'experiment_name': 'AE-779-2',
 'experiment_description': '\n',
 'software_version': 'Workbench V1.5.7.2519',
 'device': 'FirePlate-O2 [] FP96-O2',
 'device_serial': '26040013',
 'uid': '2411E508596730F5',
 'firmware': '4.13:001',
 'group': 2,
 'sensor_code': 'TC7-499-067',
 'channels': ['C02', 'E02', 'G02'],
 'settings': {'duration': '128 ms',
  'intensity': '20%',
  'amp': '400x',
  'frequency': 470,
  'crc_enable': False,
  'write_lock': False,
  'auto_flash_duration': True,
  'auto_amp': True,
  'analyte': 'oxygen',
  'fiber_type': '1 mm',
  'temperature': 'Optical Temperature Sensor on Channel 1',
  'pressure': 'internal sensor',
  'salinity': 0.0,
  'fiber_length_mm': 0},
 'calibration': {'C02': {'date_calibration_high': datetime.datetime(2026, 4, 24, 0, 0),
   'date_calibration_zero': datetime.datetime(2026, 4, 24, 0, 0),
   'dphi100': 6.944,
   'dphi0': 50.238,
   'f': 0.827,
   'm': 0.075,
   'freq': 470.0,
   'tt': -0.0035,
   'kt': 0.00874,
   'bkgdAmpl': 0.04411,
   'bkgdDphi': 0.0,
   'mt': -0.000106,
   'pressure': 998.36,
   'temp100': 20.108,
   'humidity': 100.0,
   'temp0': 21.427,
   'percentO2': 20.95},
  'E02': {'date_calibration_high': datetime.datetime(2026, 4, 24, 0, 0),
   'date_calibration_zero': datetime.datetime(2026, 4, 24, 0, 0),
   'dphi100': 6.941,
   'dphi0': 49.772,
   'f': 0.827,
   'm': 0.075,
   'freq': 470.0,
   'tt': -0.0035,
   'kt': 0.00874,
   'bkgdAmpl': 0.04411,
   'bkgdDphi': 0.0,
   'mt': -0.000106,
   'pressure': 998.36,
   'temp100': 20.108,
   'humidity': 100.0,
   'temp0': 21.427,
   'percentO2': 20.95},
  'G02': {'date_calibration_high': datetime.datetime(2026, 4, 24, 0, 0),
   'date_calibration_zero': datetime.datetime(2026, 4, 24, 0, 0),
   'dphi100': 7.017,
   'dphi0': 49.255,
   'f': 0.827,
   'm': 0.075,
   'freq': 470.0,
   'tt': -0.0035,
   'kt': 0.00874,
   'bkgdAmpl': 0.04411,
   'bkgdDphi': 0.0,
   'mt': -0.000106,
   'pressure': 998.36,
   'temp100': 20.108,
   'humidity': 100.0,
   'temp0': 21.427,
   'percentO2': 20.95}}}

In [10]:
df.iloc[1].to_dict()

{'time_s': 3.726,
 'C02_oxygen_µM': 557.0495,
 'C02_dphi': 7.136,
 'C02_signal_intensity': 60.0,
 'C02_ambient_light': 16.0,
 'C02_status': 0.0,
 'E02_oxygen_µM': 566.061523,
 'E02_dphi': 7.05,
 'E02_signal_intensity': 33.0,
 'E02_ambient_light': 16.0,
 'E02_status': 0.0,
 'G02_oxygen_µM': 553.898621,
 'G02_dphi': 7.246,
 'G02_signal_intensity': 37.0,
 'G02_ambient_light': 16.0,
 'G02_status': 0.0,
 'A02_optical_temperature': 21.723,
 'pressure': 998.0}

In [16]:
df, m = parse('testdata/workbench_V1.5.4.2482/2025-03-24_154458_Test_WB1452482/MeasurementData/B_APHOX-LX_(B Ch.1)_pH.txt')

Warning! Unknown Workbench version! Please update pyrotoolbox.

In [17]:
df

,time_s,pH,dphi,signal_intensity,ambient_light,R,status,sample_temperature
date_time,,,,,,,,
2025-03-24 15:44:58.916,0.219,7.192,39.096,204,4,0.5060,0,23.481
2025-03-24 15:45:08.776,10.080,7.192,39.096,204,6,0.5060,0,23.484
2025-03-24 15:45:18.773,20.077,7.189,39.046,204,-1,0.5079,0,23.484
2025-03-24 15:45:28.774,30.077,7.188,39.030,204,-3,0.5085,0,23.484
2025-03-24 15:45:38.774,40.077,7.189,39.057,204,1,0.5074,0,23.485
2025-03-24 15:45:48.774,50.078,7.188,39.038,204,5,0.5082,0,23.484
2025-03-24 15:45:58.773,60.077,7.186,39.005,204,1,0.5094,0,23.483
2025-03-24 15:46:08.775,70.079,7.185,38.991,204,0,0.5100,0,23.484
2025-03-24 15:46:18.777,80.081,7.187,39.012,204,2,0.5091,0,23.485
2025-03-24 15:46:28.777,90.080,7.185,38.986,204,0,0.5101,0,23.485
2025-03-24 15:46:38.778,100.081,7.185,38.992,204,0,0.5099,0,23.485
2025-03-24 15:46:48.779,110.082,7.184,38.960,204,0,0.5111,0,23.483
2025-03-24 15:46:58.777,120.080,7.184,38.966,204,0,0.5109,0,23.483
2025-03-24 15:47:08.786,130.089,7.183,38.947,205,1,0.5116,0,23.481
2025-03-24 15:47:18.777,140.081,7.185,38.977,205,1,0.5104,0,23.482
2025-03-24 15:47:28.778,150.081,7.185,38.985,204,6,0.5102,0,23.481
2025-03-24 15:47:38.778,160.081,7.184,38.965,205,1,0.5109,0,23.480
2025-03-24 15:47:48.780,170.083,7.183,38.947,205,-1,0.5117,0,23.480
2025-03-24 15:47:58.778,180.082,7.183,38.948,205,1,0.5116,0,23.479
2025-03-24 15:48:08.777,190.081,7.185,38.988,205,-2,0.5101,0,23.479
2025-03-24 15:48:18.777,200.080,7.184,38.967,205,-5,0.5109,0,23.478
2025-03-24 15:48:28.782,210.086,7.184,38.966,205,6,0.5110,0,23.478

In [18]:
m

{'experiment_name': 'Test_WB1452482',
 'experiment_description': '\n',
 'software_version': 'Workbench V1.5.4.2482',
 'device': 'AquapHOx-LX [B] APHOX-LX',
 'device_serial': '20390003',
 'uid': '24EB9B04575BA469',
 'firmware': '4.10:007',
 'channel': 1,
 'sensor_code': 'FGD7-594-838',
 'settings': {'duration': '16 ms',
  'intensity': '30%',
  'amp': '400x',
  'frequency': 3000,
  'crc_enable': False,
  'write_lock': False,
  'auto_flash_duration': False,
  'auto_amp': True,
  'analyte': 'pH',
  'fiber_type': '1 mm',
  'temperature': 'external sensor',
  'pressure': 'internal sensor',
  'salinity': 7.5,
  'fiber_length_mm': 0},
 'calibration': {'date_calibration_acid': datetime.datetime(2025, 3, 24, 0, 0),
  'date_calibration_base': datetime.datetime(2025, 3, 24, 0, 0),
  'date_calibration_offset': datetime.datetime(2025, 3, 24, 0, 0),
  'R1': 1.391446,
  'pH1': 2.276554,
  'temp1': 23.715248,
  'salinity1': 2.0,
  'R2': 0.068792,
  'pH2': 11.180096,
  'temp2': 23.5054,
  'salinity2': 6.0,
  'offset': -0.16735,
  'dphi_ref': 57.8,
  'attenuation_coefficient': 0.03593,
  'bkgdAmpl': 0.04411,
  'bkgdDphi': 0.0,
  'dsf_dye': 0.9904,
  'dtf_dye': -0.006321,
  'pka': 7.069192,
  'slope': 1.048,
  'bottom_t': -0.007805,
  'top_t': -0.00154,
  'slope_t': 0.0,
  'pka_t': -0.008985,
  'pka_is1': 2.33,
  'pka_is2': 0.25}}